### ISSUE TITLE
New Version 4.1.0

### ISSUE THREAD

**Issue by clairton** [caelum/vraptor-test#22]
When will release 4.1.0 version?

**Comment by Turini** [comment]
hey @clairton 
do you need any new feature not included in the current version?
If so I can release a new version pretty soon.

**Comment by clairton** [comment]
Only release with current feature, thanks

**Comment by Turini** [comment]
@clairton looks like the build is broken

https://pastebin.com/JeGpvAqF

is it related with your last PR? let me know if it is not, so I can investigate more.

**Comment by clairton** [comment]
Hello @Turini this error happens when run with java 8 and jsp.
With PR #23 and java 7 the build run successful.

**Comment by Turini** [comment]
great, thanks! I'll let you know when the new version is ready.

**Comment by Turini** [comment]
still not working. did you run mvn test? the output here was:

> Failed tests:   shouldExecuteLogicForward(br.com.caelum.vraptor.test.VRaptorNavigationSimpleScenariosTest): expected:</WEB-INF/jsp/test/test.jsp> but was:<null>
      shouldCompileAndExecuteAJsp(br.com.caelum.vraptor.test.VRaptorNavigationSimpleScenariosTest): Your application threw an exception: org.apache.jasper.JasperException: Unable to compile class for JSP: (..)
      shouldCompileAndExecuteAJspf(br.com.caelum.vraptor.test.VRaptorNavigationSimpleScenariosTest): expected:<[Hello world from a jspf]> but was:<[]>
      shouldCompileAndExecuteAJspWithIncludedJspf(br.com.caelum.vraptor.test.VRaptorNavigationSimpleScenariosTest): expected:<[Hello world from a jspfragment]> but was:<[]>
    
   > Tests in error: 
      shouldCauseValidationErrors(br.com.caelum.vraptor.test.VRaptorNavigationSimpleScenariosTest): WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped
    
    Tests run: 21, Failures: 4, Errors: 1, Skipped: 0

**Comment by clairton** [comment]
@Turini it's true, the same error with java 7 and 8 on PR #24.
I updated to latest vraptor version 4.1.4 and throws this

```java
Tests run: 19, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.097 sec <<< FAILURE!
shouldCauseValidationErrors(br.com.caelum.vraptor.test.VRaptorNavigationSimpleScenariosTest)  Time elapsed: 0.013 sec  <<< ERROR!
org.jboss.weld.context.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped
	at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:680)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:79)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:78)
	at br.com.caelum.vraptor.validator.Messages$Proxy$_$$_WeldClientProxy.getErrors(Unknown Source)
	at br.com.caelum.vraptor.validator.DefaultValidator.getErrors(DefaultValidator.java:173)
	at br.com.caelum.vraptor.validator.DefaultValidator.hasErrors(DefaultValidator.java:168)
	at br.com.caelum.vraptor.test.VRaptorTestResult.isValid(VRaptorTestResult.java:103)
	at br.com.caelum.vraptor.test.VRaptorNavigationSimpleScenariosTest.shouldCauseValidationErrors(VRaptorNavigationSimpleScenariosTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error: 
  shouldCauseValidationErrors(br.com.caelum.vraptor.test.VRaptorNavigationSimpleScenariosTest): WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped

```

**Comment by Turini** [comment]
I've just added travis' badge to this project, helping us to check the build status. 
i can't look at it now, but i'm going soon.

**Comment by clairton** [comment]
Hi @Turini, the problem was call VRaptorTestResult#isValid and request scope is ended.
I fix it with https://github.com/clairton/vraptor-test/commit/de60e3720b8287bcb5b72880e0475318683970ac

**Comment by Turini** [comment]
ok, it seems to be right now. thank you, Clairton. I'll let you know when it's released.

**Comment by Turini** [comment]
thank you, @clairton. but it still not compiling in java 8 envies.

**Comment by clairton** [comment]
@Turini Are you sure?
What happened?
My build run successful with jdk 7 and target/source 1.7, or jdk 8 with target/source 1.7 or 1.8.

**Comment by Turini** [comment]
@clairton I've tried in 3 different environments and I always got:

>Results :
Failed tests:   shouldCompileAndExecuteAJsp(br.com.caelum.vraptor.test.VRaptorNavigationSimpleScenariosTest): Your application threw an exception: org.apache.jasper.JasperException: Unable to compile class for JSP: (..)
  shouldCompileAndExecuteAJspf(br.com.caelum.vraptor.test.VRaptorNavigationSimpleScenariosTest): expected:<[Hello world from a jspf]> but was:<[]>
  shouldCompileAndExecuteAJspWithIncludedJspf(br.com.caelum.vraptor.test.VRaptorNavigationSimpleScenariosTest): expected:<[Hello world from a jspfragment]> but was:<[]>

Tests run: 21, Failures: 3, Errors: 0, Skipped: 0

**Comment by clairton** [comment]
I created a new PR #25 to fix it.

**Comment by Turini** [comment]
awesome. and it's done, 4.1.0 will be available in a couple hours.

**Comment by clairton** [comment]
it works, thanks @Turini
